version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: talentenportaal-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Testen2025!
      - POSTGRES_DB=TalentenPortaal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - talentenportaal-network

networks:
  talentenportaal-network:
    driver: bridge

volumes:
  postgres_data: