using TalentDataAccess.DataAccess.DataAccessObjects;

namespace TalentDataAccess.DataAccess.ExampleData
{
    public class CreateEducationDetails
    {

        public static List<EducationDetail> Create()
        {
            List<EducationDetail> list = new();

            string[] from = new string[] {
                "Sept. 1980",
                "Januari 1995",
                "03/2019",
                "09/2016",
                "01/2012",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "2010",
                "2009",
                "2007",
                "",
                "",
                "",
                "",
                "2023",
                "2023",
                "1985",
                "2002",
                "1998",
            };

            string[] to = new string[] {
                "Juli 1988",
                "December 1999",
                "09/2019",
                "03/2017",
                "12/2016",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "2020",
                "2010",
                "2009",
                "",
                "",
                "",
                "",
                "2023",
                "2023",
                "2020",
                "2002",
                "1998",
            };

            string[] names = new string[] {
                "Acteuropleiding",
                "Master Business Adminstration (MBA)",
                "Redacteren kun je leren",
                "Taxidienst voor gevorderden",
                "Office Management",
                "Software Development",
                "Vapro-C",
                "Vapro-B",
                "PSM1",
                "PSPO1",
                "Communicatie; International Event Music and Entertainment industrie",
                "Rock City Institute",
                "Juridisch Medewerker",
                "Professional Scrum Master I",
                "Wft Zorgverzekeringen 2019",
                "Wft Basis",
                "Volver Sound Academy",
                "Adecco CEO for One Month",
                "Ascensos Communicatie Training",
                  "HAVO",
                "MBO 4 Applicatie en Mediaontwikkelaar",
                "PSM1",
                "HBO Informatica",
                "Milieukunde",
                "HAVO",
                "Professional Scrum Master",
                "Developing ASP.NET MVC Web Applications",
                "Angular Development",
                "Programming in HTML 5 with Javascript and CSS3",
                "Microsoft DEV204.1x Introduction to C#",
                "Applied Science",
                "PSM1",
                "Toegepaste Psychologie",
                "Milieukunde",
                "Informatica",
                "Codeacademy C#",
                "Professional Scrum Master 1",
                "Learn C++",
                "HAN Leraren opleiding Wis-/Natuurkunde",
                "Capacity building inclusief PSM1 certificering",
                "Agile Scrum Foundation",
                "Diverse programmeertalen en operating systemen",
                "Teamleider",
                "Effectief communiceren",
            };

            string[] intitutions = new string[] {
                "Britse Beeldbuis Club (BBC)",
                "Nyenrode Business University",
                "LOI",
                "Oranje licht? Dan gas geven!",
                "HRO Rotterdam",
                "HBO",
                "",
                "",
                "Scrum.org",
                "Scrum.org",
                "HBO",
                "MBO",
                "MBO",
                "Scrum.org",
                "",
                "",
                "",
                "",
                "",
                "Trevianum Sittard",
                "Vista College Maastricht",
                "Scrum.org",
                "LOI",
                "Open Universiteit",
                "",
                "Scrum.org",
                "",
                "",
                "",
                "",
                "HBO",
                "Scrum.org",
                "HBO",
                "HBO",
                "HBO",
                "",
                "Scrum.org",
                "learncpp.com",
                "HBO",
                "Bee-Ideas",
                "",
                "",
                "",
                "",
            };

            string[] commments = new string[]
            {
                "De opleiding duurde lang door de vele ongelukken.",
                "",
                "",
                "Certificaat niet behaald.",
                "",
                "",
                "",
                "",
                "",
                "(Bezig met)",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Work in Progress",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Propedeuse",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            };

            int[] talentIds = new int[] {
                1,
                2,
                3,
                5,
                6,
                8, //Dennis
                8,
                8,
                8,
                8,
                9, //Michiel
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                10, //Kelvin
                10,
                10,
                11, //John
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                12, //Peter
                12,
                13, //Roel
                13,
                13,
                13,
                13,
                13,
                14, //Jos
                14,
                14,
                14,
                14,
                14,
            };

            for (int i = 0; i < talentIds.Length; i++)
            {
                EducationDetail educationDetail = new();
                educationDetail.Id = i + 1;
                educationDetail.DateFrom = from[i];
                educationDetail.DateTill = to[i];
                educationDetail.Name = names[i];
                educationDetail.Institution = intitutions[i];
                educationDetail.Comments = commments[i];
                educationDetail.TalentId = talentIds[i];

                list.Add(educationDetail);
            }

            return list;
        }

    }
}
